# Generated by Django 6.0.2 on 2026-02-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
    ]
